
spring:
  application:
    name: job-service

my:
  property: dev234

# Dynamic configuration setup
management:
  endpoints:
    web:
      exposure:
        include: refresh
# curl -X POST http://localhost:8081/actuator/refresh
  
